---
Name: bulkpricing
---
## Extensions
SilverCommerce\OrdersAdmin\Model\LineItem:
  extensions:
    - SilverCommerce\BulkPricing\Extensions\BulkPricingLineItem
SilverCommerce\CatalogueAdmin\Model\CatalogueProduct:
  extensions:
    - SilverCommerce\BulkPricing\Extensions\BulkPricingProduct
